---
- name: Ensure requisite apt packages are installed.
  yum: name={{ item }} state=present
  with_items:
    - pure-ftpd
    - openssl
    - python-pip

- name: Install pexpect
  pip:
    name: "pexpect"
    state: present
